### ISSUE TITLE
Stream Deck Star Citizen actions no longer firing

### ISSUE THREAD

**Issue by deaconb** [mhwlng/streamdeck-starcitizen#10]
My Star Citizen Static Button actions are no longer firing in Star Citizen or while using a test environment like Notepad++. I've uninstalled and reinstalled the 1.0.8 plugin and also tried running Stream Deck in administrative mode with no success. 

I don't believe anything has changed in my environment other than the usual updates to Windows, Star Citizen, and Stream Deck. Everything is running at its latest available version.

Examining the log file, it appears there is an issue with the XmlReader state while opening the actionmaps.xml file:

2022-11-21 11:04:20.3284|DEBUG|com.mhwlng.starcitizen|1|Logger Initialized
2022-11-21 11:04:20.3454|INFO|com.mhwlng.starcitizen|1|Init Star Citizen
2022-11-21 11:04:20.3454|INFO|com.mhwlng.starcitizen|1|F:\Program Files\Roberts Space Industries\StarCitizen\LIVE\Data.p4k
2022-11-21 11:04:38.5327|INFO|com.mhwlng.starcitizen|1|actionmaps.xml
2022-11-21 11:04:38.5513|FATAL|com.mhwlng.starcitizen|1|DProfileReader: System.InvalidOperationException: The XmlReader state should be Interactive.
   at System.Xml.Linq.XNode.ReadFrom(XmlReader reader)
   at SCJMapper_V2.SC.DProfileReader.fromActionProfile(String xml)
   at starcitizen.Program.GetKeyBindings(Object threadContext)
   at starcitizen.Program.Main(String[] args)
2022-11-21 11:04:38.5513|INFO|com.mhwlng.starcitizen|1|Finished Init Star Citizen
2022-11-21 11:04:38.5513|INFO|com.mhwlng.starcitizen|1|Plugin [com.mhwlng.starcitizen] Loading - 2 Actions Found
2022-11-21 11:04:38.6649|INFO|com.mhwlng.starcitizen|1|Plugin version: 1.0.8
2022-11-21 11:04:38.6649|INFO|com.mhwlng.starcitizen|1|Connecting to Stream Deck
2022-11-21 11:04:40.7353|INFO|com.mhwlng.starcitizen|1|Connected to Stream Deck
2022-11-21 11:04:40.7353|INFO|com.mhwlng.starcitizen|1|GlobalSettingsManager initialized
2022-11-21 11:10:04.6245|INFO|com.mhwlng.starcitizen|26|Disconnect event received
2022-11-21 11:10:04.6255|INFO|com.mhwlng.starcitizen|1|Plugin Disconnected - Exiting
2022-11-21 11:10:37.5616|DEBUG|com.mhwlng.starcitizen|1|Logger Initialized
2022-11-21 11:10:37.5896|INFO|com.mhwlng.starcitizen|1|Init Star Citizen
2022-11-21 11:10:37.6106|INFO|com.mhwlng.starcitizen|1|F:\Program Files\Roberts Space Industries\StarCitizen\LIVE\Data.p4k needs update : False
2022-11-21 11:10:37.6106|INFO|com.mhwlng.starcitizen|1|actionmaps.xml
2022-11-21 11:10:37.6465|FATAL|com.mhwlng.starcitizen|1|DProfileReader: System.InvalidOperationException: The XmlReader state should be Interactive.
   at System.Xml.Linq.XNode.ReadFrom(XmlReader reader)
   at SCJMapper_V2.SC.DProfileReader.fromActionProfile(String xml)
   at starcitizen.Program.GetKeyBindings(Object threadContext)
   at starcitizen.Program.Main(String[] args)
2022-11-21 11:10:37.6465|INFO|com.mhwlng.starcitizen|1|Finished Init Star Citizen
2022-11-21 11:10:37.6465|INFO|com.mhwlng.starcitizen|1|Plugin [com.mhwlng.starcitizen] Loading - 2 Actions Found
2022-11-21 11:10:37.8314|INFO|com.mhwlng.starcitizen|1|Plugin version: 1.0.8
2022-11-21 11:10:37.8314|INFO|com.mhwlng.starcitizen|1|Connecting to Stream Deck
2022-11-21 11:10:46.2308|INFO|com.mhwlng.starcitizen|1|Connected to Stream Deck
2022-11-21 11:10:46.2308|INFO|com.mhwlng.starcitizen|1|GlobalSettingsManager initialized

**Comment by mhwlng** [comment]
Can you please zip your plugin directory and post it here

**Comment by deaconb** [comment]
[com.mhwlng.starcitizen.sdPlugin.zip](https://github.com/mhwlng/streamdeck-starcitizen/files/10061536/com.mhwlng.starcitizen.sdPlugin.zip)

**Comment by mhwlng** [comment]
I also need the actionmaps.xml file.
can you post it here?

the error signifies that this file is empty or not valid xml ?

maybe you can try to rename/remove this file (after making a backup)  or export/import your bindings and restart the game to generate this file again.
then restart the plugin.

**Comment by deaconb** [comment]
@mhwlng , this is a little crazy. I had renamed my "Client\0\profiles\default" folder to "default.old" quite a while back to clear the settings and keep a backup. I expected Star Citizen to recreate the "default" folder, but it appears to have latched onto the files in the renamed "default.old" folder and continued running as usual. I'm guessing your plugin is hardwired to look for the folder name of "default", which it obliviously wasn't finding after the rename.

I completely removed my "default.old" folder restarted Star Citizen, which regenned the "default" folder, and restarted Stream Deck... and everything is good again. Your plug-in is working as it should.

Apologies for wasting your time on my fat-headedness. Thanks for the assist and the great work on a fantastic plug-in.

**Comment by mhwlng** [comment]
ok great :-)
