### ISSUE TITLE
Buttons not doing anything / XmlReader state should be interactive

### ISSUE THREAD

**Issue by plattdl** [mhwlng/streamdeck-starcitizen#19]
Hi, I am attempting to use this plugin and am having trouble getting any of the buttons to work. I was browsing this repo and found out about the log which is below. I had tried setting the config to point to my files manually but still no luck. StreamDeck is run as admin. I did notice the XmlReader error and was wondering if that was the issue and how to fix it. 

Thank you for your time!

```
2024-01-05 19:44:54.4958|INFO|com.mhwlng.starcitizen|88|BarRaider.SdTools.Communication.StreamDeckConnection RunAsync completed, shutting down
2024-01-05 19:44:54.5221|INFO|com.mhwlng.starcitizen|15|Disconnect event received
2024-01-05 19:44:54.5221|INFO|com.mhwlng.starcitizen|1|Plugin Disconnected - Exiting
2024-01-05 19:45:11.3359|DEBUG|com.mhwlng.starcitizen|1|Logger Initialized
2024-01-05 19:45:11.3707|INFO|com.mhwlng.starcitizen|1|Init Star Citizen
2024-01-05 19:45:11.3811|INFO|com.mhwlng.starcitizen|1|
2024-01-05 19:45:11.3811|INFO|com.mhwlng.starcitizen|1|C:\StarCitizen\LIVE\USER\Client\0\Profiles\default\actionmaps.xml
2024-01-05 19:45:11.4025|FATAL|com.mhwlng.starcitizen|1|DProfileReader: System.InvalidOperationException: The XmlReader state should be Interactive.
   at System.Xml.Linq.XNode.ReadFrom(XmlReader reader)
   at SCJMapper_V2.SC.DProfileReader.fromXML(String xml)
   at starcitizen.Program.GetKeyBindings(Object threadContext)
   at starcitizen.Program.Main(String[] args)
2024-01-05 19:45:11.4025|INFO|com.mhwlng.starcitizen|1|Finished Init Star Citizen
2024-01-05 19:45:11.4098|INFO|com.mhwlng.starcitizen|1|Plugin [com.mhwlng.starcitizen] Loading - 3 Actions Found
2024-01-05 19:45:11.7672|DEBUG|com.mhwlng.starcitizen|1|Plugin Loaded: UUID: DADCB343280E0425AE4D486269A32C4B Device Info: Devices:
[Id: D077EA89CF1CCFBE779A2985ADB5671E Type: StreamDeckClassic Size: Rows: 3 Columns: 5]
ApplicationInfo: Language: en Platform: windows Version: 6.5.0.19904
PluginInfo: Version: 1.1.1

2024-01-05 19:45:11.7672|INFO|com.mhwlng.starcitizen|1|Plugin version: 1.1.1
2024-01-05 19:45:11.7672|INFO|com.mhwlng.starcitizen|1|Connecting to Stream Deck...
2024-01-05 19:45:13.8661|INFO|com.mhwlng.starcitizen|1|Connected to Stream Deck
2024-01-05 19:45:13.8661|INFO|com.mhwlng.starcitizen|1|GlobalSettingsManager initialized
```

**Comment by mhwlng** [comment]
apparently the game files are not in C:\StarCitizen\LIVE\USER\Client\0\Profiles\default\actionmaps.xml ? or the plugin does not have access to this directoy.

you need to set up the 'real' directory in the appsettings.config file

**Comment by plattdl** [comment]
Oof, I double checked the path but apparently I needed to triple check. Got it working thanks!
