### ISSUE TITLE
Manual Convergence Distance missing

### ISSUE THREAD

**Issue by dopeghoti** [mhwlng/streamdeck-starcitizen#25]
I'd love to be able to adjust manual convergence with buttons or a dial on my Stream Deck, but the plugin does not seem to be picking these up from Vehicles/Weapons:

![image](https://github.com/user-attachments/assets/a2a6e7eb-2db1-484b-b533-1be8c4f44aef)

![image](https://github.com/user-attachments/assets/472344a8-148f-4079-bd00-7b5d3e742cea)

**Comment by mhwlng** [comment]
I don't see a key binding in your screenshot ? Did you add them ?

**Comment by mhwlng** [comment]
I added a key to one of these and I see the line appear 

(you may need to exit the keybinding screens in the game and restart streamdeck.exe after adding the key)

![image](https://github.com/user-attachments/assets/4cda962b-ef97-4696-a488-9187387226f8)

![image](https://github.com/user-attachments/assets/32febe1a-1219-4490-bab2-bc210dd0eafc)

if you don't see the key appear, make sure that you put the correct path in

%appdata%\Elgato\StreamDeck\Plugins\com.mhwlng.starcitizen.sdPlugin\appsettings.config

can I close this ticket?

**Comment by dopeghoti** [comment]
I've double-checked that I have bindings and confirmed they exist in the `actionmaps.xml`:

![image](https://github.com/user-attachments/assets/ff3851ba-7055-4582-9f4f-b51fd092cf3b)

I've also double-checked that the app config is correct and it appears to be (though I had to re-set the settings after I tried uninstalling and re-installing the plugin):

![image](https://github.com/user-attachments/assets/0273751e-3b16-4190-9e23-b61e6714a009)

I believe you that the key binds _should_ be coming up but I'm not sure why they aren't.

I do see this in `com.mhwlng.starcitizen.process0.log`:

```
Unhandled Exception: System.IO.IOException: The process cannot access the file 'E:\Program Files\Star Citizen\StarCitizen\LIVE\USER\Client\0\Profiles\default\actionmaps.xml' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at SCJMapper_V2.SC.SCDefaultProfile.ActionMaps()
   at starcitizen.Program.GetKeyBindings(Object threadContext)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at starcitizen.WorkItem.Execute()
   at starcitizen.FifoExecution.ProcessQueuedItems(Object ignored)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

However, when I check with Process Explorer, nothing has that file open.  I've even tried closing out of Star Citizen and the launcher entirely before restarting the Stream Deck software.  

Any ideas?

**Comment by mhwlng** [comment]
are you 100% sure that 'E:\Program Files\Star Citizen\StarCitizen\LIVE\USER\Client\0\Profiles\default\actionmaps.xml is the correct path ?

try starting streamdeck.exe with run as administrator 
or change the access rights to that directory

otherwise I have no idea...

**Comment by dopeghoti** [comment]
About as sure as I can be:

![image](https://github.com/user-attachments/assets/3d6ab98d-224e-4a8e-937a-f73a55340c9d)

On an a lark, I did see I have some pending OS updates to install, so I'm going to use that as a nudge to try a good old-fashioned reboot (which honestly I should have tried first, Windows being Windows) in addition to the options you just mentioned.

**Comment by dopeghoti** [comment]
Sure enough, that did the trick; sorry to have sent you on a wild goose chase.  Thanks again for your work on this; it's very useful!
